### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SakuraTokoyomi** [Nyanm/Saccharomyces-cerevisiae#11]
More information at https://github.com/Nyanm/Saccharomyces-cerevisiae
[INFO] FileHandler.encoding = utf-8
[INFO] config.cfg load complete.
map size  :2000
card num  :AA6BD894564572E3
db dir    :D:/newSDVX/asphyxia-core/savedata/sdvx@asphyxia.db
game dir  :D:/newSDVX/contents/data
output    :D:/newSDVX/b50
skin name :gen6
language  :ZH
is init   :True
version   :2024060401
[INFO] Load aka_db, level_table, search_db from ./data
Traceback (most recent call last):
  File "app.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "genre\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "genre\gen6\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "genre\gen6\main.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "parse\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "parse\asp.py", line 156, in <module>
  File "parse\asp.py", line 68, in __init__
IndexError: list index out of range
[15416] Failed to execute script 'app' due to unhandled exception!

**Comment by SakuraTokoyomi** [comment]
草，把map size改成3000就行了，估计是更新曲目多了导致数组越界
