### ISSUE TITLE
Bugs in plot function

### ISSUE THREAD

**Issue by MuTong233** [Nyanm/Saccharomyces-cerevisiae#2]
Error Reported by Pre-built exe version 1.22:
--------------------------------------------------
libpng warning: iCCP: known incorrect sRGB profile
[WARNING] Something wrong happens in the plot function, only will the text message be returned.
Traceback (most recent call last):
  File "genre\gen6\main.py", line 408, in plot_b50
  File "genre\gen6\tools.py", line 291, in generate_std_profile
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
---------------------------------------------------
donno think this is my fault lo
btw 世宇什么时候更新啊不会真摆了吧不会吧不会吧

**Comment by Nyanm** [comment]
573更新第二章时把部分文件结构改了，包括但不限于appeal card的文件名
我慢慢改（

**Comment by Nyanm** [comment]
573更新第二章时连带改了部分文件结构
我慢慢改
这个玩意真难用（
