### ISSUE TITLE
invalid literal for int() with base 10: '' 错误

### ISSUE THREAD

**Issue by BillyGong** [Nyanm/Saccharomyces-cerevisiae#4]
当我尝试生成best 50的时候会遇到这个错误
```
2022/09/04 10:40:35 [DEBUG] app.py(276) - Get user operator 1
2022/09/04 10:40:35 [ERROR] app.py(291) - Fatal error occurs, please report the following message to developer.
Traceback (most recent call last):
  File "app.py", line 289, in <module>
  File "app.py", line 278, in input_handler
  File "app.py", line 49, in _1_get_b50
  File "app.py", line 32, in _get_b50
  File "genre\gen6\main.py", line 365, in plot_b50
  File "genre\gen6\tools.py", line 118, in get_diff
ValueError: invalid literal for int() with base 10: ''
```
莫名 `diff_table[int(inf_ver) - 2][m_type]` 这里的`inf_ver`是一个空字符。
有人遇到过这个问题嘛！谢谢大佬们了！

**Comment by BillyGong** [comment]
解决了，我发现是我没有打50首歌导致搜不到空的歌名的信息。
