### ISSUE TITLE
appeal card 读取错误，无法生成plot

### ISSUE THREAD

**Issue by ztren** [Nyanm/Saccharomyces-cerevisiae#8]
```
libpng warning: iCCP: known incorrect sRGB profile
[WARNING] Something wrong happens in the plot function, only will the text message be returned.
Traceback (most recent call last):
  File "genre\gen6\main.py", line 410, in plot_b50
    std_profile = generate_std_profile(profile, vol_force)
  File "genre\gen6\tools.py", line 294, in generate_std_profile
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

查了一下应该是tools.py的问题，我头像ID是0607，也就是ap_03_R0107
但是tools.py里`get_ap_card`只有第二位是5的时候才会加R

~~不PR了 因为好像没有人看~~
交PR了

**Comment by LyceenAiro** [comment]
是新版本的ID导致的吗，我可以看看有没有什么解决方案
不知道你是第一次生成gen6皮肤包还是之前已经正常使用过了
毕竟这个软件已经很久没人维护了，肯定会出现各种问题

**Comment by LyceenAiro** [comment]
[x] 已经合并了pr
